### ISSUE TITLE
Websocket working only on localhost

### ISSUE THREAD

**Issue by vimalraj-a** [redstone-dart/redstone_web_socket#2]
I cannot connect with websocket by IP address or 127.0.0.1

Code 
import 'package:redstone/redstone.dart' as app;
import 'package:redstone_web_socket/redstone_web_socket.dart';
import 'dart:io';

void main() {
  app.setupConsoleLog();

  //install web socket handlers
  app.addPlugin(getWebSocketPlugin());

  app.start(); 
}
@WebSocketHandler("/ws")
onConnection(websocket) {
  websocket.listen((message) {
    print(message);
    websocket.add("echo $message");
  });
}

above code working only when i connect with localhost

**Comment by Pacane** [comment]
What error does it give you?

**Comment by vimalraj-a** [comment]
Message never received from browser. But, when I use 'localhost' able to receive message.
